### PR TITLE
draft: Async with Goroutines

### LINKED ISSUE #14: Lua help wanted: make commands async using coroutines
I'm not super familiar with Lua coroutines so this will probably be a lot of work, but I'm thinking some of this stuff can be made async using coroutines. On the Go side it's extremely simple and trivial to make stuff async using Goroutines, but we'd need to use Lua coroutines on the Lua side.

Basically I'm thinking like:

Lua makes a request to Go, and suspends coroutine execution => Go does some async stuff, then calls a Lua function => the Lua function called by Go resumes the original Lua coroutine

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #14 

Makes stuff non-blocking where possible/where it makes sense.

### CODE REVIEW

**Comment by mrjones2014** [comment]
@tsyroid mind giving this branch a spin and seeing if I screwed anything up?

@olimorris I can't remember if you're using this plugin or not. if so mind giving it a test?

**Comment by olimorris** [comment]
Will absolutely give this a test tomorrow 💪🏼

**Comment by tsyroid** [comment]
Kicked all tires I could think of.
Zero issues of any sort to report.
Definitely notice the app is much more ‘responsive’ (when switching
profiles or simply signing in/out) with coroutines.

👏

**Comment by mrjones2014** [comment]
> Definitely notice the app is much more ‘responsive’

awesome, that was the hope. Going to spend some more time thinking about what else can be made async.

**Comment by mrjones2014** [comment]
Been testing this quite a bit. Going to go ahead and mere 🎉 🌮

**Pull request merged**
