### PR TITLE
Fix duplicate op-Security tags in docs

### PR DESCRIPTION
**Pull request by aaronkollasch**
Duplicate tags prevents the generation of helptags (`:helptags`), leading to error `Vim:E154`. This PR gives the duplicate `op-Security` tags unique names to fix this.

### CODE REVIEW

**Comment by mrjones2014** [comment]
Hey there, thanks for the PR. These docs are autogenerated, which means this problem will just come back if we fix it this way. 

I think what we should do is port over the docs generation from one of my other plugins where I’ve already fixed this issue.

I’ll fix this when I get a chance this week, unless you’d like to give it a try in this PR.

Here’s the GitHub Actions job: https://github.com/mrjones2014/legendary.nvim/blob/master/.github/workflows/gen-docs-txt.yml

which uses this script: https://github.com/mrjones2014/legendary.nvim/blob/master/vimdoc-gen.lua

which is run via this Makefile command: https://github.com/mrjones2014/legendary.nvim/blob/master/Makefile#L26

**Comment by aaronkollasch** [comment]
Hey, I've made a commit which ports over docs generation from the files you suggested. What's the best way to test the workflow?

**Comment by mrjones2014** [comment]
Thanks for doing that, I've made a few small changes and tested it locally. This should be good to go!

**Review by mrjones2014 — APPROVED** [review]

**Comment by mrjones2014** [comment]
No problem! Thanks for pointing out the issue!

**Pull request merged**
