### PR TITLE
1Password Sidebar!!!!!

### LINKED ISSUE #42: 1Password Sidebar
Would be cool to have a sidebar where you could pin items (or I wonder if the CLI can get “favorites” items from 1Password) and have different actions on `<CR>` keypress. 

For login items, it would open and fill, for Secure Notes, it would open the note.

Each item type could use a different NerdFont icon. Potentially mapping popular URLs like GitHub to the GitHub NerdFont logo icon for GitHub login, for example.

this would all be static/cached, just a list of titles with UUID and icon, and open either in a sidebar or a select (maybe configurable).

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #42 

Pending issues:

- #49
- #51 
- #52

### CODE REVIEW

**Comment by mrjones2014** [comment]
@tsyroid mind giving this a spin?

**Comment by mrjones2014** [comment]
Some specific things to test:

- [ ] Does the sidebar open/close properly?
- [ ] Try opening a buffer while cursor is in sidebar -- does the sidebar properly move the opened buffer to a new window?
- [ ] Try creating a split inside the sidebar -- does the split open to the next non-sidebar buffer? (should only have one sidebar window at a time)
- [ ] Do the keymappings work? (described here in the README.md updates)
- [ ] Are you able to customize the keybindings, sidebar sections, and width via the config?
- [ ] Are you able to override the highlighting groups? (groups described in README.md updates)

**Comment by tsyroid** [comment]
Test results (so far...)
#1 (above): Yes, usually. I had one occasion of unexpected behavior but I can't remember the steps I did to trigger it. Going to consider this an 'operator error' until I can recreate.
#2: Usually. Once I opened a new buffer (`:e init.lua`; with cursor in sidebar) and it opened the file in the sidebar (wrong!). Tried to recreate but I can't ATM. I can recreate the following error consistently: with cursor in sidebar, type command `:e`. Opens a new buffer in sidebar (wrong!).
#3: Yes.
#4: ? Your link to the README.md (keymappings) is bust. I don't see any sidebar specific keymaps anywhere. Is this what you're referring to?

**Comment by mrjones2014** [comment]
@tsyroid keymappings described here: https://github.com/mrjones2014/op.nvim/pull/50/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R133

**Comment by mrjones2014** [comment]
`:e` issue fixed.

**Comment by tsyroid** [comment]
#4: Keymaps work from sidebar. But I have a niggle. When I open a note for editing (in 1Password app), cursor should land in the item I want to edit, not the search bar. Don't know if you can control this or not. Suggest you add a default keymap that toggles sidebar, cuz that's the most common thing I'm going to do regarding your sidebar (`go`?).
#2: Confirm resolved.
#5: Yes, I can successfully reconfigure sidebar.

**Comment by mrjones2014** [comment]
>When I open a note for editing (in 1Password app), cursor should land in the item I want to edit, not the search bar.

For me, the cursor lands in the item title field of the edit view 🤔 

But this isn't something I can control from the Neovim/CLI side.

>Suggest you add a default keymap that toggles sidebar

I personally don't like it when plugins handle global keymappings, I prefer to handle these in my own config so keymappings can all be defined in the same place -- currently this is only defining keymappings local to the sidebar buffer.

I can add a recommended sidebar toggle keymap to the README.md though.

**Comment by tsyroid** [comment]
OK, understand both (Here, cursor consistently lands in search bar).

Not sure what you’re getting at with test item #6 (overriding highlight
groups)? Don’t see any reference to highlighting groups in README or config
defaults.

/tom

**Comment by mrjones2014** [comment]
Huh, somehow my README.md changes about the sidebar highlight groups got lost, I've added them back. Basically, can you override the highlight groups by running `:hi OpSidebarHeader guifg=blue ctermfg=blue` for all the highlight groups and see the colors change in the sidebar:

- `OpSidebarHeader` - the section header text
- `OpSidebarItem` - the text for items under a section header
- `OpSidebarFavoriteIcon` - the star icon used for the 'Favorites' section header
- `OpSidebarIconDefault` - all other icons in the sidebar (e.g. item category icons)

**Comment by tsyroid** [comment]
OK, see it now (pulled successfully). Not going to test highlights; I
leave colorscheme shit to people with more patience than me. Toss this one
to Oli 😉

From everything I’ve seen last night and today, I think you’re safe to
merge this. Might some small niggles we’ve missed, but all the big rocks
are behaving.

I still want to mess around with adding a function to ’sidebar.actions’,
but that ain’t gonna be happening today.

Nice work!

/tom

**Comment by mrjones2014** [comment]
>Once I opened a new buffer (:e init.lua; with cursor in sidebar) and it opened the file in the sidebar (wrong!). Tried to recreate but I can't ATM.

I figured this out -- it happens when you immediately open the sidebar before anything else because I'm getting the "previous window" on open, and in this case there is no "previous window" because you've only seen one window so far. It's fixed now.

Going to merge this then, thanks for testing! 🎉🌮

**Pull request merged**
